INSERT INTO Iscrizione(IdCorso, UsernameUtente)
VALUES 
((SELECT IdCorso FROM Corso WHERE Titolo = 'Corso di pizza napoletana' AND Anno = 2025), 'Zeb89'),
((SELECT IdCorso FROM Corso WHERE Titolo = 'Corso di cucina italiana' AND Anno = 2025), 'giuliano.laccetti'),
((SELECT IdCorso FROM Corso WHERE Titolo = 'Corso di cucina cinese' AND Anno = 2025), 'luigi.bros'),
((SELECT IdCorso FROM Corso WHERE Titolo = 'Corso di cucina messicana' AND Anno = 2025), 'mario.bros'),
((SELECT IdCorso FROM Corso WHERE Titolo = 'Corso di cucina giapponese' AND Anno = 2025), 'IL_NERDONE_11'),
((SELECT IdCorso FROM Corso WHERE Titolo = 'Corso di cucina indiana' AND Anno = 2025), 'bohqualcosaboh'),
((SELECT IdCorso FROM Corso WHERE Titolo = 'Corso di cucina francese' AND Anno = 2025), 'pete_990'),
((SELECT IdCorso FROM Corso WHERE Titolo = 'Corso di cucina spagnola' AND Anno = 2025), 'xFireFox27'),
((SELECT IdCorso FROM Corso WHERE Titolo = 'Corso di cucina americana' AND Anno = 2025), 'Zeb89'),
((SELECT IdCorso FROM Corso WHERE Titolo = 'Corso di cucina mediterranea' AND Anno = 2025), 'antonio.capuozzo'),
((SELECT IdCorso FROM Corso WHERE Titolo = 'Corso di pasticceria' AND Anno = 2025), 'giordano.bruno'),
((SELECT IdCorso FROM Corso WHERE Titolo = 'Corso di panificazione' AND Anno = 2025), 'francesco.deluca'),
((SELECT IdCorso FROM Corso WHERE Titolo = 'Corso di cucina italiana' AND Anno = 2025), 'alessandro.rossi'),
((SELECT IdCorso FROM Corso WHERE Titolo = 'Corso di cucina cinese' AND Anno = 2025), 'federico.borghi'),
((SELECT IdCorso FROM Corso WHERE Titolo = 'Corso di cucina messicana' AND Anno = 2025), 'matteo.ruggiero'),
((SELECT IdCorso FROM Corso WHERE Titolo = 'Corso di cucina giapponese' AND Anno = 2025), 'stefano.martini'),
((SELECT IdCorso FROM Corso WHERE Titolo = 'Corso di cucina indiana' AND Anno = 2025), 'giorgio.bianchi'),
((SELECT IdCorso FROM Corso WHERE Titolo = 'Corso di cucina francese' AND Anno = 2025), 'luca.verdi'),
((SELECT IdCorso FROM Corso WHERE Titolo = 'Corso di cucina spagnola' AND Anno = 2025), 'marco.storti'),
((SELECT IdCorso FROM Corso WHERE Titolo = 'Corso di cucina americana' AND Anno = 2025), 'andrea.simpatico'),
((SELECT IdCorso FROM Corso WHERE Titolo = 'Corso di cucina mediterranea' AND Anno = 2025), 'elena.scalzi'),
((SELECT IdCorso FROM Corso WHERE Titolo = 'Corso di pasticceria' AND Anno = 2025), 'chiara.gallo'),
((SELECT IdCorso FROM Corso WHERE Titolo = 'Corso di panificazione' AND Anno = 2025), 'sara.botticelli'),
((SELECT IdCorso FROM Corso WHERE Titolo = 'Corso di cucina italiana' AND Anno = 2025), 'giulia.manzoni'),
((SELECT IdCorso FROM Corso WHERE Titolo = 'Corso di cucina cinese' AND Anno = 2025), 'martina.rinaldi'),
((SELECT IdCorso FROM Corso WHERE Titolo = 'Corso di cucina messicana' AND Anno = 2025), 'alice.gaudino'),
((SELECT IdCorso FROM Corso WHERE Titolo = 'Corso di cucina giapponese' AND Anno = 2025), 'francesca.ferrari'),
((SELECT IdCorso FROM Corso WHERE Titolo = 'Corso di cucina indiana' AND Anno = 2025), 'renato.cicala'),
((SELECT IdCorso FROM Corso WHERE Titolo = 'Corso di cucina francese' AND Anno = 2025), 'davide.buonaurio'),
((SELECT IdCorso FROM Corso WHERE Titolo = 'Corso di cucina spagnola' AND Anno = 2025), 'davide.esposito'),
((SELECT IdCorso FROM Corso WHERE Titolo = 'Corso di cucina americana' AND Anno = 2025), 'morgan.desantis'),
((SELECT IdCorso FROM Corso WHERE Titolo = 'Corso di cucina mediterranea' AND Anno = 2025), 'pocho'),
((SELECT IdCorso FROM Corso WHERE Titolo = 'Corso di pasticceria' AND Anno = 2025), 'matador'),
((SELECT IdCorso FROM Corso WHERE Titolo = 'Corso di panificazione' AND Anno = 2025), 'marekiaro'),
((SELECT IdCorso FROM Corso WHERE Titolo = 'Corso di cucina italiana' AND Anno = 2025), 'ciro'),
((SELECT IdCorso FROM Corso WHERE Titolo = 'Corso di cucina cinese' AND Anno = 2025), 'kalidou.koulibaly'),
((SELECT IdCorso FROM Corso WHERE Titolo = 'Corso di cucina messicana' AND Anno = 2025), 'kvaradona'),
((SELECT IdCorso FROM Corso WHERE Titolo = 'Corso di cucina giapponese' AND Anno = 2025), 'donkey.kong'),
((SELECT IdCorso FROM Corso WHERE Titolo = 'Corso di cucina indiana' AND Anno = 2025), 'diddy.kong'),
((SELECT IdCorso FROM Corso WHERE Titolo = 'Corso di cucina francese' AND Anno = 2025), 'cranky.kong'),
((SELECT IdCorso FROM Corso WHERE Titolo = 'Corso di cucina spagnola' AND Anno = 2025), 'dixie.kong'),
((SELECT IdCorso FROM Corso WHERE Titolo = 'Corso di cucina americana' AND Anno = 2025), 'funky.kong'),
((SELECT IdCorso FROM Corso WHERE Titolo = 'Corso di cucina mediterranea' AND Anno = 2025), 'akira.toriyama'),
((SELECT IdCorso FROM Corso WHERE Titolo = 'Corso di cucina italiana' AND Anno = 2025), 'goku.son'),
((SELECT IdCorso FROM Corso WHERE Titolo = 'Corso di panificazione' AND Anno = 2025), 'bulma.briefs'),
((SELECT IdCorso FROM Corso WHERE Titolo = 'Corso di cucina italiana' AND Anno = 2025), 'trunks.briefs'),
((SELECT IdCorso FROM Corso WHERE Titolo = 'Corso di cucina cinese' AND Anno = 2025), 'gohan.son'),
((SELECT IdCorso FROM Corso WHERE Titolo = 'Corso di cucina messicana' AND Anno = 2025), 'goten.son'),
((SELECT IdCorso FROM Corso WHERE Titolo = 'Corso di cucina giapponese' AND Anno = 2025), 'majin.buu'),
((SELECT IdCorso FROM Corso WHERE Titolo = 'Corso di cucina indiana' AND Anno = 2025), 'dio.brando'),
((SELECT IdCorso FROM Corso WHERE Titolo = 'Corso di cucina francese' AND Anno = 2025), 'joseph.joestar'),
((SELECT IdCorso FROM Corso WHERE Titolo = 'Corso di cucina spagnola' AND Anno = 2025), 'jotaro.kujo'),
((SELECT IdCorso FROM Corso WHERE Titolo = 'Corso di cucina americana' AND Anno = 2025), 'giorno.giovanna'),
((SELECT IdCorso FROM Corso WHERE Titolo = 'Corso di cucina mediterranea' AND Anno = 2025), 'josuke.higashikata'),
((SELECT IdCorso FROM Corso WHERE Titolo = 'Corso di pasticceria' AND Anno = 2025), 'jolyne.cujoh'),
((SELECT IdCorso FROM Corso WHERE Titolo = 'Corso di panificazione' AND Anno = 2025), 'enrico.pucci'),
((SELECT IdCorso FROM Corso WHERE Titolo = 'Corso di cucina italiana' AND Anno = 2025), 'william.zeppeli'),
((SELECT IdCorso FROM Corso WHERE Titolo = 'Corso di cucina cinese' AND Anno = 2025), 'caesar.zeppeli'),
((SELECT IdCorso FROM Corso WHERE Titolo = 'Corso di cucina francese' AND Anno = 2025), 'rohan.kishibe'),
((SELECT IdCorso FROM Corso WHERE Titolo = 'Corso di cucina giapponese' AND Anno = 2025), 'suzy.q'),
((SELECT IdCorso FROM Corso WHERE Titolo = 'Corso di cucina indiana' AND Anno = 2025), 'yasuho.hirose');
((SELECT IdCorso FROM Corso WHERE Titolo = 'Corso di cucina francese' AND Anno = 2025), 'kira.yoshikage'),
((SELECT IdCorso FROM Corso WHERE Titolo = 'Corso di cucina spagnola' AND Anno = 2025), 'giorgio.bianchi'),
((SELECT IdCorso FROM Corso WHERE Titolo = 'Corso di cucina americana' AND Anno = 2025), 'luca.verdi'),
((SELECT IdCorso FROM Corso WHERE Titolo = 'Corso di cucina mediterranea' AND Anno = 2025), 'marco.storti'),
((SELECT IdCorso FROM Corso WHERE Titolo = 'Corso di pasticceria' AND Anno = 2025), 'andrea.simpatico'),
((SELECT IdCorso FROM Corso WHERE Titolo = 'Corso di panificazione' AND Anno = 2025), 'elena.scalzi'),
((SELECT IdCorso FROM Corso WHERE Titolo = 'Corso di cucina italiana' AND Anno = 2025), 'chiara.gallo'),
((SELECT IdCorso FROM Corso WHERE Titolo = 'Corso di cucina cinese' AND Anno = 2025), 'sara.botticelli'),
((SELECT IdCorso FROM Corso WHERE Titolo = 'Corso di cucina messicana' AND Anno = 2025), 'giulia.manzoni'),
((SELECT IdCorso FROM Corso WHERE Titolo = 'Corso di cucina giapponese' AND Anno = 2025), 'martina.rinaldi'),
((SELECT IdCorso FROM Corso WHERE Titolo = 'Corso di cucina indiana' AND Anno = 2025), 'alice.gaudino'),
((SELECT IdCorso FROM Corso WHERE Titolo = 'Corso di cucina francese' AND Anno = 2025), 'francesca.ferrari'),
((SELECT IdCorso FROM Corso WHERE Titolo = 'Corso di cucina spagnola' AND Anno = 2025), 'renato.cicala'),
((SELECT IdCorso FROM Corso WHERE Titolo = 'Corso di cucina americana' AND Anno = 2025), 'davide.buonaurio'),
((SELECT IdCorso FROM Corso WHERE Titolo = 'Corso di cucina mediterranea' AND Anno = 2025), 'davide.esposito'),
((SELECT IdCorso FROM Corso WHERE Titolo = 'Corso di pasticceria' AND Anno = 2025), 'morgan.desantis'),
((SELECT IdCorso FROM Corso WHERE Titolo = 'Corso di panificazione' AND Anno = 2025), 'pocho'),
((SELECT IdCorso FROM Corso WHERE Titolo = 'Corso di cucina italiana' AND Anno = 2025), 'matador'),
((SELECT IdCorso FROM Corso WHERE Titolo = 'Corso di cucina cinese' AND Anno = 2025), 'marekiaro'),
((SELECT IdCorso FROM Corso WHERE Titolo = 'Corso di cucina messicana' AND Anno = 2025), 'ciro'),
((SELECT IdCorso FROM Corso WHERE Titolo = 'Corso di cucina giapponese' AND Anno = 2025), 'kalidou.koulibaly'),
((SELECT IdCorso FROM Corso WHERE Titolo = 'Corso di cucina indiana' AND Anno = 2025), 'kvaradona'),
((SELECT IdCorso FROM Corso WHERE Titolo = 'Corso di cucina spagnola' AND Anno = 2025), 'donkey.kong'),
((SELECT IdCorso FROM Corso WHERE Titolo = 'Corso di cucina spagnola' AND Anno = 2025), 'diddy.kong'),
((SELECT IdCorso FROM Corso WHERE Titolo = 'Corso di cucina americana' AND Anno = 2025), 'cranky.kong'),
((SELECT IdCorso FROM Corso WHERE Titolo = 'Corso di cucina italiana' AND Anno = 2025), 'mario.bros'),
((SELECT IdCorso FROM Corso WHERE Titolo = 'Corso di cucina messicana' AND Anno = 2025), 'francesco.deluca'),







