INSERT INTO Ricetta(Nome, Descrizione)
VALUES
       --Cucina Italiana
       ('Pasta al Pomodoro', 'Una semplice pasta con salsa di pomodoro'),
       ('Spaghetti Aglio Olio e Peperoncino', 'Spaghetti con aglio, olio d''oliva e peperoncino.'),
       ('Bruschetta al Pomodoro', 'Pane tostato condito con pomodori freschi e basilico.'),
       ('Insalata Caprese', 'Insalata di mozzarella, pomodori e basilico.'),
       ('Pasta e Patate', 'Pasta con patate e un soffritto di altre verdure.'),
       ('Carbonara', 'Pasta con crema di uovo pastorizzato, pecorino romano e pepe condita con del guanciale croccante.'),
       ('Pesto alla Genovese', 'Un pesto di basilico fresco, pinoli e parmigiano. Utilizzato come condimento per pasta o bruschette.'),
       ('Polpette al Sugo', 'Polpette di carne e mollica di pane bagnata cotte in un sugo di pomodoro.'),
       ('Parmigiana di Melanzane', 'Preparazione in teglia a base di melanzane fritte, salsa di pomodoro e mozzarella e parmigiano.'),
       ('Arancini di Riso', 'Sfere di riso risottato allo zafferano con diverse possibilità di ripieno, impanate e fritte.'),
       ('Caponata', 'Stufato di melanzane, pomodori, sedano, cipolle e olive.'),
       ('Cacciucco', 'Zuppa a base di pesce fresco, crostacei e molluschi.'),
       ('Zuppa di Cozze', 'Cozze, crostacei, polpo e molluschi cucinate nella propria acqua e pomodorini, servita su crostini di pane e condita con olio piccante. Tradizionalmente mangiata il giovedì Santo.'),
       ('Frittata di Maccheroni', 'Ricetta di recupero, si tratta di una frittata di pasta avanzata condita a piacere.'),
       ('Pasta alla Norma', 'Pasta con pomodoro, melanzane fritte e ricotta infornata.'),
       ('Pasta alla Puttanesca', 'Pasta con un sugo di pomodoro, capperi e olive nere.'),
       ('Pasta al Forno', 'Ricetta di recupero, si tratta di pasta avanzata, condita a piacere e ripassata in forno.'),
       ('Ragù alla Bolognese', 'Sugo di pomodoro con carne macinata e un soffritto di varie verdure.'),
       ('Sartù di Riso', 'Riso condito con ragù di carne, piselli e mozzarella, cotto in forno.'),
       ('Risotto ai Funghi Porcini', 'Un risotto cremoso con funghi porcini freschi.'),
       ('Risotto alla Milanese', 'Risotto con zafferano e brodo di carne.'),
       ('Risotto al Nero di Seppia', 'Risotto con seppie e il loro inchiostro.'),
       ('Spaghetti al Nero di Seppia', 'Spaghetti con seppie e il loro inchiostro.'),
       ('Spaghetti all''Acqua Pazza', 'Spaghetti conditi con un sugo di pomodoro, aglio, prezzemolo ed un brodo ottenuto dagli scarti di pesce.'),
       ('Spaghetti alle Vongole', 'Spaghetti con vongole veraci, aglio e prezzemolo.'),
       ('Spaghetti con le Sarde', 'Spaghetti con sarde fresche, finocchietto selvatico, pinoli, olive nere e pangrattato'),
       ('Sarde a Beccafico', 'Sarde farcite con pangrattato, pinoli e uvetta, arrotolate e cotte in forno.'),
       ('Cotoletta alla Milanese', 'Fetta di lombo di vitello impanata e fritta in burro.'),
       ('Fritto Misto', 'Frittura di pesce e verdure.'),
       ('Calamari Fritti', 'Anelli di calamari impastellati e fritti.'),
       ('Insalata di Polpo', 'Insalata di polpo con patate, prezzemolo e olio d''oliva.'),
       ('Orata al Sale', 'Orata cotta in crosta di sale.'),
       ('Fritto di Paranza', 'Frittura di pesce e crostacei.'),
       ('Fiore di Zucca Fritto', 'Fiore di zucca ripieno di ricotta e pepe, impastellato e fritto.'),
       ('Lasagna alla Bolognese', 'Strati di pasta alternati a strati di ragù di carne e besciamella.'),
       --Pizza Napoletana
       ('Pizza Provola e Pepe', 'Pizza con base pomodoro condita con provola affumicata, pepe e basilico.'),
       ('Pizza Marinara', 'Pizza con base pomodoro condita con aglio e origano.'),
       ('Pizza Margherita', 'Pizza con base pomodoro condita con mozzarella e basilico.'),
       ('Pizza Romana', 'Pizza con base pomodoro condita con acciughe e capperi e olive.'),
       ('Pizza Quattro Stagioni', 'Pizza con base pomodoro e mozzarella sezionata in quattro spicchi conditi rispettivamente con: funghi, carciofini sott''olio, prosciutto cotto e olive.'),
       ('Pizza Quattro Formaggi', 'Pizza con base di quattro diversi formaggi: mozzarella, gorgonzola, parmigiano e fontina.'),
       ('Pizza Ortolana', 'Pizza con base Fior di Latte condita con diversi ortaggi di stagione.'),
       ('Pizza Diavola', 'Pizza con base pomodoro condita con salame piccante e peperoncino'),
       ('Pizza Capricciosa', 'Pizza con base pomodoro condita con funghi, carciofini sott''olio, prosciutto cotto e olive.'),
       ('Pizza Fritta', 'Base di impasto per la pizza condita per metà con pomodoro, provola, ricotta, salumi e pepe, richiusa su se stessa e fritta in olio bollente.'),
       ('Montanara', 'Pizza fritta condita con pomodoro, basilico e parmigiano.'),
       ('Pizza Filetto', 'Pizza con base Fior di Latte condita con pomodorini freschi tagliati a filetto e basilico.'),
       ('Pizza Salsiccia e Friarielli', 'Pizza con base Fior di Latte condita con salsiccia e friarielli.'),
       --Cucina Spagnola
       ('Tapas', 'Piccole porzioni di cibo servite come antipasto.'),
       ('Tortilla di Patate', 'Frittata di uova e patate cotta in padella.'),
       ('Tortilla di Cipolle', 'Frittata di uova e cipolle cotta in padella.'),
       ('Gazpacho', 'Zuppa fredda a base di pomodori, cetrioli, peperoni e cipolla.'),
       ('Paella', 'Riso cotto con zafferano e vari ingredienti come pollo, coniglio, frutti di mare o verdure.'),
       ('Churros', 'Dolce di patata fritto a forma di bastoncino, spesso servito con cioccolata calda.'),
       ('Polpo a la Gallega', 'Polpo lessato e condito con paprika, olio d''oliva e sale grosso.'),
       ('Crema Catalana', 'Dolce al cucchiaio a base di crema pasticcera con una crosta di zucchero caramellato.'),
       ('Empanada Fritta', 'Pasta con ripieni di vario genere e fritta.'),
       ('Empanada al Forno', 'Pasta con ripieni di vario genere e cotta in forno.'),
       --Cucina Messicana
       ('Chili di Carne', 'Stufato di carne macinata con fagioli, verdure e varie spezie e odori.'),
       ('Nachos con Formaggio', 'Tortilla chips di mais con formaggio fuso.'),
       ('Guacamole', 'Salsa a base di avocado, lime, cipolla e pomodoro.'),
       ('Tacos', 'Pasta di mais a forma di conchiglia, ripiena di chili, verdure e formaggio.'),
       ('Burrito', 'Sfoglia di pasta simile alle piadine ripiena di chili e formaggio, avvolta su se stessa e piastrata.'),
       ('Quesadilla', 'Tortilla di mais ripiena di formaggio e altri ingredienti, cotta in padella.'),
       --Cucina Giapponese
       ('Ramen', 'Zuppa di noodle giapponese servita in un brodo saporito e condito con diversi ingredienti.'),
       ('Nigiri', 'Riso sushi servito con pesce crudo posato sopra.'),
       ('Sashimi', 'Fette di pesce crudo.'),
       ('Maki', 'Riso sushi avvolto in alga nori con ripieno di pesce e verdure.'),
       ('Uramaki', 'Ripieno di pesce e verdure avvolto in alga nori, a sua volta avvolta in riso sushi'),
       ('Tempura', 'Verdure o pesce fritti in una pastella leggera.'),
       ('Gyoza', 'Ravioli giapponesi ripieni di carne e verdure, cotti al vapore o alla piastra.'),
       ('Onigiri', 'Polpette di riso ripiene di pesce o verdure, avvolte in alga nori.'),
       ('Curry Giapponese', 'Stufato di carne e verdure cotto in una salsa di curry dolce.'),
       ('Ramen di Carne', 'Udon in brodo di carne con carne di maiale, uova e verdure'),
       ('Ramen di Pesce', 'Udon in brodo di pesce con pesce, uova e verdure.'),
       ('Soba', 'Noodle giapponesi a base di grano saraceno da intingere in salsa tsuyu, serviti freddi o caldi.'),
       ('Tonkatsu', 'Cotoletta di maiale impanata e fritta, servita con salsa tonkatsu.'),
       ('Okonomiyaki', 'Frittata giapponese con cavolo, carne e altri ingredienti, cotta su una piastra.'),
       ('Takoyaki', 'Polpette di pastella ripiene di polpo, cotte su una piastra speciale.'),
       ('Taiyaki', 'Dolce a forma di pesce ripieno di marmellata di fagioli dolci o altre marmellate.'),
       ('Mochi', 'Dolce di pasta di riso glutinoso, ripieno di fagioli dolci.'),
       --Cucina Cinese
       ('Baozi', 'Conosciuti come ravioli cinesi, sono panini al vapore ripieni di carne o verdure.'),
       ('Dim Sum', 'Piccole porzioni di cibo servite in cestini di bambù, a base di carne, pesce o verdure.'),
       ('Riso Fritto', 'Riso saltato in padella con uova e verdure.'),
       ('Involtini Primavera', 'Involtini di sfoglia di riso ripieni di verdure.'),
       ('Anatra alla Pechinese', 'Anatra arrosto con pelle croccante'),
       ('Pollo Kung Pao', 'Pollo saltato in padella con arachidi, peperoni e salsa di soia.'),
       --Cucina Americana
       ('Beef Jerky', 'Carne di manzo speziata ed essiccata.'),
       ('Hamburger', 'carne macinata di manzo pressata in forma di disco e cotta alla griglia.'),
       ('NewYork Style Pizza', 'Pizza molto grande dalla base sottile, servita in grandi fette.'),
       ('Chicago Style Pizza', 'Pizza con base spessa, ripiena di formaggio e salsa di pomodoro.'),
       ('Alette di Pollo', 'Alette di pollo marinate e condite con salsa barbecue, cotte al forno.'),
       ('Pollo Fritto', 'Pollo marinato, impanato e fritto.'),
       ('Hot Dog', 'Wurstel di carne servito in un panino e condito con salse.'),
       ('Pulled Pork', 'Carne di maiale speziata e cotta lentamente in affumicatrice.'),
       ('Mac and Cheese', 'Pasta condita con formaggio fuso.'),
       ('Fettuccine Alfredo', 'Pasta condita con burro, panna e parmigiano.'),
       ('Brownies', 'Dolce a base di cioccolato e burro di forma quadrata.'),
       ('Cheesecake', 'Dolce di formaggio cremoso con base di biscotto.'),
       ('NewYork Cheesecake', 'Cheesecake cotta in forno ricoperta di frutta o cioccolato.'),
       --Cucina Indiana
       ('Pollo Tandoori', 'Pollo marinato in yogurt e spezie, cotto in forno tandoor.'),
       ('Curry', 'Carne o Verdure cotti in un mix di spezie e latte di cocco.'),
       ('Pane Naan', 'Pane indiano cotto in forno tandoor.'),
       ('Samosa', 'Involtini di sfoglia sottile di forma triangolare, ripieni di carne o verdure.'),
       ('Chicken Tikka', 'Pollo marinato e cotto in forno, alla griglia o al curry.'),
       --Cucina Francese
       ('Soupe a l''oignon', 'Zuppa a base di cipolle caramellate e brodo, servita con crostini di pane.'),
       ('Escargot', 'Lumache cotte in burro all''aglio e prezzemolo.'),
       ('Coq au Vin', 'Pollo cotto in vino rosso con funghi, cipolle e pancetta.'),
       ('Ratatouille', 'Stufato di verdure estive.'),
       ('Boeuf Bourguignon', 'Stufato di manzo cotto in vino rosso con funghi e cipolle.'),
       ('Crepes', 'Pasta sottile e morbida, farcita con ingredienti dolci o salati.'),
       ('Croissant', 'Dolce di pasta sfoglia a forma di mezzaluna.'),
       ('Macarons', 'Dolcetti di pasta di mandorle.'),
       ('Omelette', 'Frittata tipica francese dal cuore cremoso.'),
       ('Quiche Lorraine', 'Torta salata con uova, panna e pancetta.'),
       --Panificazione
       ('Pancarré', 'Pane bianco morbido, usato per fare tramezzini e toast.'),
       ('Pane Bianco', 'Pane bianco con crosta sottile.'),
       ('Pane Integrale', 'Pane integrale con crosta spessa.'),
       ('Pane ai Cereali', 'Pane con una miscela di cereali e semi.'),
       ('Focaccia', 'Panificato piatto condito con olio d''oliva e sale.'),
       ('Focaccia Ligure', 'Focaccia alta e soffice condita con olio d''oliva e sale.'),
       ('Focaccia Barese', 'Focaccia condita con pomodorini, olive e origano.'),
       ('Pane di Segale', 'Pane scuro e fitto, fatto con farina di segale.'),
       ('Panini all''Olio', 'Piccoli panini morbidi.'),
       ('Pane Carasau', 'Pane tipico della Sardegna, sottile e croccante.'),
       ('Pane Toscano', 'Pane caratterizzato dall''assenza di sale nell''impasto.'),
       ('Pane di Altamura', 'Pane tipico della Puglia, fatto con semola di grano duro.'),
       ('Sfilatino', 'Pane lungo e sottile, utilizzato per fare panini.'),
       ('Baguette', 'Pane lungo e sottile, tipico della cucina francese.'),
       ('Ciabatta', 'Pane croccante all''esterno e morbido all''interno, spesso utilizzato per fare panini piastrati.'),
       ('Piadina Romagnola', 'Sfoglia di pasta sottile, cotta su una piastra.'),
       ('Pizza in Teglia', 'Pizza cotta in teglia e farcita a piacere.'),
       ('Pizza alla Pala', 'Pizza lunga e sottile, cotta su una pala di legno.'),
       ('Casatiello', 'Panificato rustico tipico della Pasqua napoletana, farcito con salumi e formaggi.'),
       --Pasticceria
       ('Torta di Mele', 'Dolce a base di mele e cannella.'),
       ('Torta al Cioccolato', 'Dolce a base di cacao, farina, uova e zucchero.'),
       ('Torta di Ricotta', 'Dolce a base di ricotta, zucchero e uova.'),
       ('Torta Caprese', 'Dolce a base di cacao e mandorle, spolverata con zucchero a velo.'),
       ('Torta della Nonna', 'Torta di pasta frolla ripiena di crema pasticcera e pinoli.'),
       ('Torta di Ciliegie', 'Dolce a base di ciliegie fresche, farina, zucchero e uova.'),
       ('Torta Ricotta e Pere', 'Dolce a base di ricotta e pere con una base di pasta di nocciole.'),
       ('Biscotto all''Amarena', 'Biscotto con crosta di zucchero e ripieno di amarene.'),
       ('Cantucci', 'Biscotti secchi alle mandorle.'),
       ('Torta Sacher', 'Torta a base di cacao e marmellata di albicocche, ricoperta di cioccolato fondente temperato.'),
       ('Strudel di Mele', 'Dolce a base di mele, uvetta e cannella avvolto in una pasta sottile.'),
       ('Baklava', 'Dolce a base di pasta fillo, noci e miele.'),
       ('Babà al Rum', 'Dolce lievitato imbevuto in una bagna di rum.'),
       ('Zeppole di San Giuseppe', 'Dolce di pasta choux farcita con crema pasticcera e amarene.'),
       ('Sfogliatella Riccia', 'Dolce di pasta sfoglia ripieno di ricotta, semola e canditi.'),
       ('Sfogliatella Frolla', 'Dolce di pasta frolla ripieno di ricotta, semola e canditi.'),
       ('Pastiera Napoletana', 'Dolce pasquale a base di grano e ricotta.'),
       ('Migliaccio', 'Dolce a base di semola e ricotta.'),
       ('Tiramisu', 'Dolce composto da strati di savoiardi inzuppati nel caffè e strati di mascarpone con spolverata finale di cacao.'),
       ('Panna Cotta', 'Dolce al cucchiaio a base di panna e gelatina.'),
       ('Budino al Cioccolato', 'Dolce al cucchiaio a base di cacao e latte.'),
       ('Creme brulée', 'Dolce al cucchiaio a base di crema pasticcera con una crosta di zucchero caramellato.'),
       ('Gelato', 'Dolce freddo a base di latte, proponibile in diversi gusti.'),
       ('Sorbetto', 'Dolce freddo a base di frutta e ghiaccio.'),
       ('Crostata di Frutta', 'Dolce a base di pasta frolla ripiena di crema pasticcera e coperta di frutta fresca e gelatina.'),
       ('Torrone', 'Dolce a base di mandorle e miele, preparato nel periodo della Commemorazione dei Defunti.'),
       ('Panettone', 'Dolce natalizio a base di farina, uova, burro e canditi.'),
       ('Colomba Pasquale', 'Dolce pasquale a forma di colomba, ripieno di canditi e con crosta di zucchero e mandorle.'),
       ('Pandoro', 'Dolce natalizio a forma di stella, alto e soffice, spolverato con zucchero a velo.');
