INSERT INTO Ingrediente(Nome, Allergene, UnitàMisura)
VALUES
    -- Pasta e cereali
    ('Spaghetti', true, 'g'),
    ('Penne', true, 'g'),
    ('Rigatoni', true, 'g'),
    ('Linguine', true, 'g'),
    ('Fusilli', true, 'g'),
    ('Paccheri', true, 'g'),
    ('Sfoglia per lasagne', true, 'g'),
    ('Riso Carnaroli', false, 'g'),
    ('Riso basmati', false, 'g'),
    ('Udon', true, 'g'),
    ('Noodles', true, 'g'),
    ('Soba', true, 'g'),
    ('Farina 00', true, 'g'),
    ('Farina integrale', true, 'g'),
    ('Farina di segale', true, 'g'),
    ('Semola di grano duro', true, 'g'),
    ('Grano cotto', true, 'g'),
    
    -- Verdure e ortaggi
    ('Aglio', false, 'spicchi'),
    ('Cipolla bianca', false, 'g'),
    ('Cipolla rossa', false, 'g'),
    ('Cipollotto', false, 'g'),
    ('Scalogno', false, 'g'),
    ('Sedano', false, 'g'),
    ('Carote', false, 'g'),
    ('Patate', false, 'g'),
    ('Pomodori San Marzano Pelati', false, 'g'),
    ('Pomodorini ciliegino', false, 'g'),
    ('Passata di pomodoro', false, 'ml'),
    ('Concentrato di pomodoro', false, 'g'),
    ('Melanzane', false, 'g'),
    ('Zucchine', false, 'g'),
    ('Peperoni', false, 'g'),
    ('Peperoncino', false, 'pz'),
    ('Basilico', false, 'foglie'),
    ('Prezzemolo', false, 'g'),
    ('Rosmarino', false, 'g'),
    ('Origano', false, 'g'),
    ('Timo', false, 'g'),
    ('Finocchietto selvatico', false, 'g'),
    ('Friarielli', false, 'g'),
    ('Spinaci', false, 'g'),
    ('Rucola', false, 'g'),
    ('Lattuga', false, 'g'),
    ('Cetrioli', false, 'g'),
    ('Avocado', false, 'g'),
    ('Piselli', false, 'g'),
    ('Fagioli cannellini', false, 'g'),
    ('Fagioli borlotti', false, 'g'),
    ('Fagioli neri', false, 'g'),
    ('Ceci', false, 'g'),
    ('Lenticchie', false, 'g'),
    ('Olive nere', false, 'g'),
    ('Olive verdi', false, 'g'),
    ('Capperi sotto sale', false, 'g'),
    
    -- Funghi
    ('Funghi porcini', false, 'g'),
    ('Champignon', false, 'g'),
    ('Funghi shiitake', false, 'g'),
    ('Fungo Rosso', false, 'pz'),
    ('Fungo Chiodino', false, 'g'),
    ('Tartufo nero', false, 'g'),
    
    -- Pesce
    ('Salmone', true, 'g'),
    ('Tonno', true, 'g'),
    ('Orata', true, 'g'),
    ('Branzino', true, 'g'),
    ('Sogliola', true, 'g'),
    ('Merluzzo', true, 'g'),
    ('Sarde', true, 'g'),
    ('Acciughe', true, 'g'),
    ('Acciughe sott''olio', true, 'g'),
    ('Sgombro', true, 'g'),
    ('Rana pescatrice', true, 'g'),
    ('Dentice', true, 'g'),
    ('San Pietro', true, 'g'),
    
    -- Molluschi e crostacei
    ('Vongole veraci', true, 'g'),
    ('Cozze', true, 'g'),
    ('Telline', true, 'g'),
    ('Seppie', true, 'g'),
    ('Calamari', true, 'g'),
    ('Polpo', true, 'g'),
    ('Moscardini', true, 'g'),
    ('Gamberi', true, 'g'),
    ('Gamberetti', true, 'g'),
    ('Scampi', true, 'g'),
    ('Granchi', true, 'g'),
    ('Astice', true, 'g'),
    ('Aragosta', true, 'g'),
    ('Inchiostro di seppia', true, 'ml'),
    
    -- Carni
    ('Manzo macinato', false, 'g'),
    ('Vitello', false, 'g'),
    ('Lombo di vitello', false, 'g'),
    ('Braciole di maiale', false, 'g'),
    ('Lonza di maiale', false, 'g'),
    ('Pancetta', false, 'g'),
    ('Guanciale', false, 'g'),
    ('Speck', false, 'g'),
    ('Prosciutto crudo', false, 'g'),
    ('Prosciutto cotto', false, 'g'),
    ('Salame piccante', false, 'g'),
    ('Salsiccia', false, 'g'),
    ('Pollo intero', false, 'g'),
    ('Petto di pollo', false, 'g'),
    ('Cosce di pollo', false, 'g'),
    ('Alette di pollo', false, 'g'),
    ('Anatra', false, 'g'),
    ('Coniglio', false, 'g'),
    ('Agnello', false, 'g'),
    
    -- Latticini e formaggi
    ('Mozzarella di bufala', true, 'g'),
    ('Fior di latte', true, 'g'),
    ('Provola', true, 'g'),
    ('Parmigiano Reggiano', true, 'g'),
    ('Pecorino Romano', true, 'g'),
    ('Ricotta fresca', true, 'g'),
    ('Ricotta infornata', true, 'g'),
    ('Mascarpone', true, 'g'),
    ('Formaggio Spalmabile', true, 'g'),
    ('Formaggio cheddar', true, 'g'),
    ('Latte intero', true, 'ml'),
    ('Panna fresca', true, 'ml'),
    ('Panna da cucina', true, 'ml'),
    ('Burro', true, 'g'),
    ('Yogurt greco', true, 'ml'),
    
    -- Uova
    ('Uova di gallina', true, 'pz'),
    ('Tuorli d''uovo', true, 'pz'),
    ('Albumi', true, 'pz'),
    
    -- Oli e condimenti
    ('Olio extravergine d''oliva', false, 'ml'),
    ('Olio di semi', false, 'ml'),
    ('Aceto balsamico', false, 'ml'),
    ('Aceto di vino bianco', false, 'ml'),
    ('Sale fino', false, 'g'),
    ('Sale grosso', false, 'g'),
    ('Pepe nero', false, 'g'),
    ('Pepe bianco', false, 'g'),
    ('Zafferano', false, 'g'),
    ('Paprika dolce', false, 'g'),
    ('Paprika piccante', false, 'g'),
    ('Curry in polvere', false, 'g'),
    ('Curcuma', false, 'g'),
    ('Cannella', false, 'g'),
    ('Noce moscata', false, 'g'),
    
    -- Frutta secca e semi
    ('Pinoli', true, 'g'),
    ('Mandorle', true, 'g'),
    ('Noci', true, 'g'),
    ('Nocciole', true, 'g'),
    ('Arachidi', true, 'g'),
    ('Uvetta', false, 'g'),
    
    -- Frutta fresca
    ('Limoni', false, 'pz'),
    ('Lime', false, 'pz'),
    ('Arance', false, 'pz'),
    ('Mele', false, 'g'),
    ('Pere', false, 'g'),
    ('Ciliegie', false, 'g'),
    ('Amarene', false, 'g'),
    ('Fragole', false, 'g'),
    ('Mirtilli', false, 'g'),
    ('Lamponi', false, 'g'),
    ('Ananas', false, 'g'),
    
    -- Pane e panificati
    ('Pane bianco', true, 'g'),
    ('Mollica di pane', true, 'g'),
    ('Pangrattato', true, 'g'),
    ('Crostini', true, 'pz'),
    ('Pane per hamburger', true, 'pz'),
    ('Tortilla di mais', true, 'pz'),
    ('Tortilla di grano', true, 'pz'),
    ('Piadina', true, 'pz'),
    
    -- Brodi e salse
    ('Brodo di carne', false, 'ml'),
    ('Brodo di pollo', false, 'ml'),
    ('Brodo vegetale', false, 'ml'),
    ('Brodo di pesce', true, 'ml'),
    ('Besciamella', true, 'ml'),
    ('Ragù bolognese', false, 'ml'),
    ('Salsa barbecue', false, 'ml'),
    ('Salsa worcestershire', true, 'ml'),
    ('Salsa piccante', false, 'ml'),
    ('Maionese', true, 'ml'),
    ('Ketchup', false, 'ml'),
    ('Senape', false, 'ml'),
    
    -- Ingredienti asiatici
    ('Alga nori', false, 'fogli'),
    ('Alga wakame', false, 'g'),
    ('Miso', true, 'g'),
    ('Mirin', false, 'ml'),
    ('Sake', false, 'ml'),
    ('Zenzero fresco', false, 'g'),
    ('Wasabi', false, 'g'),
    ('Latte di cocco', false, 'ml'),
    ('Salsa di soia', true, 'ml'),
    ('Salsa teriyaki', true, 'ml'),
    ('Salsa tsuyu', true, 'ml'),
    ('Salsa tonkatsu', true, 'ml'),
    ('Tempura mix', true, 'g'),
    
    -- Dolci e pasticceria
    ('Zucchero', false, 'g'),
    ('Zucchero di canna', false, 'g'),
    ('Zucchero a velo', false, 'g'),
    ('Miele', false, 'g'),
    ('Sciroppo d''acero', false, 'ml'),
    ('Cacao amaro', false, 'g'),
    ('Cioccolato fondente', true, 'g'),
    ('Cioccolato al latte', true, 'g'),
    ('Cioccolato bianco', true, 'g'),
    ('Nutella', true, 'g'),
    ('Marmellata', false, 'g'),
    ('Confettura di albicocche', false, 'g'),
    ('Savoiardi', true, 'g'),
    ('Biscotti', true, 'g'),
    ('Caffè espresso', false, 'ml'),
    ('Liquore al caffè', false, 'ml'),
    ('Rum', false, 'ml'),
    ('Marsala', false, 'ml'),
    ('Amaretto', false, 'ml'),
    ('Crema pasticcera', true, 'ml'),
    ('Gelatina', false, 'g'),
    ('Lievito per dolci', false, 'g'),
    ('Lievito di birra', false, 'g'),
    ('Bicarbonato', false, 'g'),
    ('Vaniglia', false, 'g'),
    ('Estratto di vaniglia', false, 'ml'),
    ('Canditi', false, 'g'),
    
    -- Vari
    ('Ghiaccio', false, 'g'),
    ('Acqua', false, 'ml'),
    ('Vino bianco', false, 'ml'),
    ('Vino rosso', false, 'ml'),
    ('Birra', false, 'ml'),
    ('Carciofini sott''olio', false, 'g'),
    ('Pomodori secchi', false, 'g'),
    ('Tortilla chips', true, 'g');