CREATE TABLE Notifica (
    IdNotifica VARCHAR(1000) PRIMARY KEY,
    UsernameChef VARCHAR(1000) NOT NULL,
    Oggetto VARCHAR(1000) NOT NULL,
    Testo VARCHAR(1000),
    DataInvio TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT FK_notifica_chef FOREIGN KEY (UsernameChef) REFERENCES Chef(Username)

)